name: Ready the code and deploy

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Coping the codes
        uses: actions/checkout@v6

      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: check node version
        run: node -v

      - name: install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test

  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Coping the codes
        uses: actions/checkout@v6

      - name: install dependencies
        run: npm install

      - name: Build the codes
        run: npm run build

  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Deploy the codes
        run: echo "Deploying the code..."
